nelmio_cors:
    # defaults: # we want to avoid using defaults to ensure we explicitly define all settings
    #     allow_credentials: true
    #     allow_origin: ['http://localhost:4200']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    #     max_age: 3600
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
        'login':
            allow_credentials: true
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
        'logout':
            allow_credentials: true
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
